MOTION_SENSOR_PIN:
  type: integer
  nullable: true
  min: 1

FACE_LANDMARK_THRESHOLD:
  type: float
  required: true
  min: 0.0
  max: 1.0

SECONDS_TO_CAPTURE_FRAMES:
  type: integer
  required: true
  min: 1

PICTURE_HIGH_RESOLUTION:
  type: integer
  required: true

PICTURE_WIDTH_RESOLUTION:
  type: integer
  required: true

CASCADE_CLASSIFIER:
  type: string
  required: true

SHAPE_PREDICTOR:
  type: string
  required: true

FACE_RECOGNITION_MODEL:
  type: string
  required: true

FACE_ENCODINGS_DIR:
  type: string
  required: true

UNKNOWN_PERSON_NAME:
  type: string
  required: true

INSTANCE_HOST:
  type: string
  required: true

INSTANCE_PORT:
  type: integer
  required: true
